# only specify project name here, all instances of 
# {{project_name}} will be replaced with actual project name
project_name: 'project_name'
host: 'host'
user: 'user'

uwsgi:
  import: '.uwsgi/bootstrap.py'
  module: '{{project_name}}:app'
  master: 'true'
  processes: '2'
  socket: '/tmp/{{project_name}}.sock'
  chmod-socket: '660'
  vacuum: 'true'
  die-on-term: 'true'


nginx:
  listen: '80'
  server_name: '_'
  location: '/'
  location_keys:
    include: 'uwsgi_params'
    uwsgi_pass: 'unix:/tmp/{{project_name}}.sock'
